BEGIN;

SELECT pg_catalog.pg_advisory_xact_lock(
  pg_catalog.hashtext('20260822_018_catalogos_maestros_canonicos')
);

DO $$
DECLARE
  master_table TEXT;
  required_table TEXT;
BEGIN
  IF pg_catalog.current_schema() IS DISTINCT FROM 'public' THEN
    RAISE EXCEPTION 'Esquema invalido: se esperaba public';
  END IF;
  FOREACH required_table IN ARRAY ARRAY[
    'schema_migrations','clasificacion_actividad_pld_version','clasificacion_actividad_pld_item',
    'cat_actividades_vulnerables_generales','cat_operaciones_vulnerables',
    'actividad_vulnerable_operaciones'
  ] LOOP
    IF pg_catalog.to_regclass('public.' || required_table) IS NULL THEN
      RAISE EXCEPTION 'Falta public.%',required_table;
    END IF;
  END LOOP;
  FOREACH master_table IN ARRAY ARRAY['cat_actividades_economicas','cat_giros_mercantiles'] LOOP
    IF pg_catalog.to_regclass('public.' || master_table) IS NULL THEN
      RAISE EXCEPTION 'Falta public.%',master_table;
    END IF;
    IF (
      SELECT pg_catalog.count(*)
      FROM pg_catalog.pg_attribute a
      WHERE a.attrelid=pg_catalog.to_regclass('public.' || master_table)
        AND a.attnum>0 AND NOT a.attisdropped
    )<>6 OR (
      SELECT pg_catalog.count(*) FROM (VALUES
        ('id','pg_catalog.int8'::pg_catalog.regtype,-1,true),
        ('clave','pg_catalog.varchar'::pg_catalog.regtype,24,true),
        ('descripcion','pg_catalog.varchar'::pg_catalog.regtype,504,true),
        ('activo','pg_catalog.bool'::pg_catalog.regtype,-1,true),
        ('created_at','pg_catalog.timestamptz'::pg_catalog.regtype,-1,true),
        ('updated_at','pg_catalog.timestamptz'::pg_catalog.regtype,-1,true)
      ) expected(nombre,tipo,typmod,no_nula)
      JOIN pg_catalog.pg_attribute a
        ON a.attrelid=pg_catalog.to_regclass('public.' || master_table)
       AND a.attname=expected.nombre AND a.attnum>0 AND NOT a.attisdropped
       AND a.atttypid=expected.tipo AND a.atttypmod=expected.typmod
       AND a.attnotnull=expected.no_nula
    )<>6 THEN
      RAISE EXCEPTION 'Contrato de columnas incompatible en public.%',master_table;
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM pg_catalog.pg_constraint c
      WHERE c.conrelid=pg_catalog.to_regclass('public.' || master_table)
        AND c.contype='p' AND c.convalidated
        AND c.conkey=ARRAY[(SELECT a.attnum FROM pg_catalog.pg_attribute a
          WHERE a.attrelid=c.conrelid AND a.attname='id' AND a.attnum>0 AND NOT a.attisdropped)]::SMALLINT[]
    ) OR NOT EXISTS (
      SELECT 1 FROM pg_catalog.pg_constraint c
      WHERE c.conrelid=pg_catalog.to_regclass('public.' || master_table)
        AND c.contype='u' AND c.convalidated
        AND c.conkey=ARRAY[(SELECT a.attnum FROM pg_catalog.pg_attribute a
          WHERE a.attrelid=c.conrelid AND a.attname='clave' AND a.attnum>0 AND NOT a.attisdropped)]::SMALLINT[]
    ) THEN
      RAISE EXCEPTION 'PK o UNIQUE incompatible en public.%',master_table;
    END IF;
  END LOOP;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.schema_migrations
    WHERE migration_key='20260821_017_clasificacion_av_familia_canonica'
  ) OR NOT EXISTS (
    SELECT 1 FROM public.schema_migrations
    WHERE migration_key='20260822_018_catalogos_maestros_canonicos'
  ) THEN
    RAISE EXCEPTION 'DOWN bloqueado: falta migration key 017 o 018';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.schema_migrations
    WHERE migration_key>'20260822_018_catalogos_maestros_canonicos'
  ) THEN
    RAISE EXCEPTION 'DOWN bloqueado: existe una migracion posterior a 018';
  END IF;
  IF EXISTS (
    SELECT 1 FROM pg_catalog.pg_constraint c
    WHERE c.contype='f'
      AND c.confrelid IN (
        'public.cat_actividades_economicas'::pg_catalog.regclass,
        'public.cat_giros_mercantiles'::pg_catalog.regclass
      )
  ) THEN
    RAISE EXCEPTION 'DOWN bloqueado: existen FK entrantes no autorizadas';
  END IF;
END
$$;

CREATE TEMP TABLE expected_master_018(
  tipo_catalogo TEXT NOT NULL,
  clave TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  expected_id BIGINT NOT NULL,
  PRIMARY KEY(tipo_catalogo,clave),
  UNIQUE(tipo_catalogo,expected_id)
) ON COMMIT DROP;
INSERT INTO expected_master_018 VALUES
('ACTIVIDAD_ECONOMICA_PF','1000000','NO APLICA',2),
('ACTIVIDAD_ECONOMICA_PF','1110100','AGRICULTURA Y SILVICULTURA - ADMINISTRADORES O TRABAJADORES AGRICOLAS',3),
('ACTIVIDAD_ECONOMICA_PF','1110400','AGRICULTURA Y SILVICULTURA - ADMINISTRADORES O TRABAJADORES SILVICOLAS Y FORESTALES',4),
('ACTIVIDAD_ECONOMICA_PF','1220100','GANADERIA - APICULTORES',5),
('ACTIVIDAD_ECONOMICA_PF','1220200','GANADERIA - ADMINISTRADORES, CRIADORES O SUPERVISORES AVICOLAS Y GANADEROS',6),
('ACTIVIDAD_ECONOMICA_PF','1330200','PESCA Y ACUACULTURA - PESCADORES Y TRABAJADORES EN LA CRIA Y CULTIVO DE ESPECIES MARINAS',7),
('ACTIVIDAD_ECONOMICA_PF','2130100','MINERIA, EXTRACCION Y SUMINISTRO - TECNICOS GEOLOGICOS Y DE MINERALES',8),
('ACTIVIDAD_ECONOMICA_PF','2140100','MINERIA, EXTRACCION Y SUMINISTRO - INGENIEROS, OPERADORES O AYUDANTES EN LA EXTRACCION Y REFINACION MINERA',9),
('ACTIVIDAD_ECONOMICA_PF','2210100','MINERIA, EXTRACCION Y SUMINISTRO - AYUDANTES EN LA PERFORACION DE POZOS DE PETROLEO Y GAS NATURAL',10),
('ACTIVIDAD_ECONOMICA_PF','2240200','MINERIA, EXTRACCION Y SUMINISTRO - INGENIEROS PETROLEROS',11),
('ACTIVIDAD_ECONOMICA_PF','2420100','MINERIA, EXTRACCION Y SUMINISTRO - OPERADORES DE CENTRALES O SISTEMAS  DE ENERGIA ELECTRICAS',12),
('ACTIVIDAD_ECONOMICA_PF','2420200','MINERIA, EXTRACCION Y SUMINISTRO - OPERADORES DE MAQUINAS DE VAPOR',13),
('ACTIVIDAD_ECONOMICA_PF','2530100','MINERIA, EXTRACCION Y SUMINISTRO - GERENTE, SUPERVISOR U OPERADORES DE  TRATAMIENTO Y POTABILIZACION, ABASTECIMIENTO Y RECOLECCION DE AGUA',14),
('ACTIVIDAD_ECONOMICA_PF','3130100','CONSTRUCCION - DECORADORES DE INTERIORES',15),
('ACTIVIDAD_ECONOMICA_PF','3130300','CONSTRUCCION -  INGENIEROS, TECNICOS Y OPERADORES DE LA CONSTRUCCION',16),
('ACTIVIDAD_ECONOMICA_PF','3310300','CONSTRUCCION - COLOCADORES DE PRODUCTOS PREFABRICADOS EN INMUEBLES',17),
('ACTIVIDAD_ECONOMICA_PF','3310400','CONSTRUCCION - PINTORES',18),
('ACTIVIDAD_ECONOMICA_PF','3310600','CONSTRUCCION - VIDRIEROS',19),
('ACTIVIDAD_ECONOMICA_PF','3410200','CONSTRUCCION - REPARADORES DE VIAS DE COMUNICACION',20),
('ACTIVIDAD_ECONOMICA_PF','3420100','CONSTRUCCION - PLOMEROS E INSTALADORES DE TUBERIA',21),
('ACTIVIDAD_ECONOMICA_PF','3420200','CONSTRUCCION - ARQUITECTOS',22),
('ACTIVIDAD_ECONOMICA_PF','4130300','MECANICA - MECANICOS DE EQUIPO PESADO',23),
('ACTIVIDAD_ECONOMICA_PF','4130500','MECANICA - INGENIERO O MECANICOS INSTALADORES DE MAQUINARIA INDUSTRIAL',24),
('ACTIVIDAD_ECONOMICA_PF','4131000','MECANICA - INGENIERO O TECNICO EN MECANICA DE VEHICULOS TERRESTRES, AEREOS Y ACUATICOS',25),
('ACTIVIDAD_ECONOMICA_PF','4230200','ELECTRICIDAD - INGENIEROS O TECNICOS ELECTRICISTAS',26),
('ACTIVIDAD_ECONOMICA_PF','4230500','ELECTRICIDAD - TECNICOS EN REFRIGERACION, AIRE ACONDICIONADO Y CALEFACCION',27),
('ACTIVIDAD_ECONOMICA_PF','4330100','ELECTRONICA - MECANICOS DE INSTRUMENTOS INDUSTRIALES',28),
('ACTIVIDAD_ECONOMICA_PF','4330200','ELECTRONICA - INGENIERO O TECNICOS EN  ELECTRONICA',29),
('ACTIVIDAD_ECONOMICA_PF','4430200','INFORMATICA - INGENIERO O TECNICOS PROGRAMADORES EN INFORMATICA',30),
('ACTIVIDAD_ECONOMICA_PF','4440100','INFORMATICA - PROFESIONISTAS O TECNICOS DE SISTEMAS DE INFORMACION Y PROCESAMIENTO DE DATOS',31),
('ACTIVIDAD_ECONOMICA_PF','4530200','TELECOMUNICACIONES - INGENIERO, INSTALADORES Y REPARADORES DE EQUIPOS Y ACCESORIOS DE TELECOMUNICACIONES',32),
('ACTIVIDAD_ECONOMICA_PF','4530500','TELECOMUNICACIONES - TELEGRAFISTAS Y RADIO-OPERADORES',33),
('ACTIVIDAD_ECONOMICA_PF','4630100','PROCESOS INDUSTRIALES - INGENIERO O TECNICOS INDUSTRIAL Y DE PRODUCCION',34),
('ACTIVIDAD_ECONOMICA_PF','4640300','PROCESOS INDUSTRIALES - INGENIEROS METALURGICOS Y DE MATERIALES',35),
('ACTIVIDAD_ECONOMICA_PF','5110100','MINERALES NO METALICOS - OPERADORES O TRABAJADORES DE VIDRIO Y CONCRETO',36),
('ACTIVIDAD_ECONOMICA_PF','5121300','MINERALES NO METALICOS - OPERADORES DE MAQUINAS PROCESADORAS DE MINERALES NO METALICOS',37),
('ACTIVIDAD_ECONOMICA_PF','5210100','METALES - SUPERVISORES U OPERADORES DE PROCESAMIENTO Y FUNDICION DE METALES',38),
('ACTIVIDAD_ECONOMICA_PF','5310700','ALIMENTOS Y BEBIDAS - TRABAJADORES EN LA ELABORACION  Y PROCESAMIENTO DE ALIMENTOS, BEBIDAS Y TABACO',39),
('ACTIVIDAD_ECONOMICA_PF','5410100','TEXTILES Y PRENDAS DE VESTIR - TRABAJADORES EN LA PRODUCCION DE TEXTILES, PRENDAS DE VESTIR Y CALZADO',40),
('ACTIVIDAD_ECONOMICA_PF','5420700','TEXTILES Y PRENDAS DE VESTIR - TRABAJADORES DE REPARACION DE PRENDAS DE VESTIR Y CALZADO',41),
('ACTIVIDAD_ECONOMICA_PF','5510100','MADERA, PAPEL, Y PIEL - TRABAJADORES EN LA FABRICACION DE MUEBLES O PRODUCTOS DE MADERA Y/O PIEL',42),
('ACTIVIDAD_ECONOMICA_PF','5610200','PRODUCTOS QUIMICOS - TRABAJADORES EN EL PROCESAMIENTO Y FABRICACION DE PRODUCTOS QUIMICOS Y FARMACOQUIMICAS',43),
('ACTIVIDAD_ECONOMICA_PF','5710200','PRODUCTOS METALICOS Y DE HULE Y PLASTICO - TRABAJADORES  EN LA FABRICACION DE PRODUCTOS METALICOS, DE HULE Y PLASTICOS',44),
('ACTIVIDAD_ECONOMICA_PF','5720800','PRODUCTOS METALICOS Y DE HULE Y PLASTICO - ENSAMBLADORES Y ACABADORES DE PRODUCTOS DE PLASTICO',45),
('ACTIVIDAD_ECONOMICA_PF','5720900','PRODUCTOS METALICOS Y DE HULE Y PLASTICO - FABRICANTES DE HERRAMIENTAS Y TROQUELES',46),
('ACTIVIDAD_ECONOMICA_PF','5721000','PRODUCTOS METALICOS Y DE HULE Y PLASTICO - HERREROS Y FORJADORES',47),
('ACTIVIDAD_ECONOMICA_PF','5721100','PRODUCTOS METALICOS Y DE HULE Y PLASTICO - JOYEROS Y ORFEBRES',48),
('ACTIVIDAD_ECONOMICA_PF','5722900','PRODUCTOS METALICOS Y DE HULE Y PLASTICO - SOLDADORES Y OXICORTADORES',49),
('ACTIVIDAD_ECONOMICA_PF','5730600','PRODUCTOS METALICOS Y DE HULE Y PLASTICO - TRABAJADORES EN EL ENSAMBLADO DE VEHICULOS, MOLDEADO, LAMINADO Y MONTAJE DE PIEZAS METALICAS, HULE O PLASTICO',50),
('ACTIVIDAD_ECONOMICA_PF','5731100','PRODUCTOS METALICOS Y DE HULE Y PLASTICO - SUPERVISORES EN LA FABRICACION Y MONTAJE DE ARTICULOS DEPORTIVOS, DE JUGUETES Y SIMILARES',51),
('ACTIVIDAD_ECONOMICA_PF','5810200','PRODUCTOS ELECTRICOS Y ELECTRONICOS - TRABAJADORES EN LA FABRICACION DE PRODUCTOS ELECTRICOS Y ELECTRONICOS',52),
('ACTIVIDAD_ECONOMICA_PF','5910400','PRODUCTOS IMPRESOS - TRABAJADORES EN LA ELABORACION DE PRODUCTOS IMPRESOS',53),
('ACTIVIDAD_ECONOMICA_PF','6120100','TRANSPORTE FERROVIARIO - CONDUCTORES Y OPERADORES DE TREN SUBTERRANEO Y DE TREN LIGERO',54),
('ACTIVIDAD_ECONOMICA_PF','6120200','TRANSPORTE FERROVIARIO - TRABAJADORES DE FERROCARRILES',55),
('ACTIVIDAD_ECONOMICA_PF','6220100','TRANSPORTE TERRESTRE - CONDUCTORES DE VEHICULOS DE TRANSPORTE, SERVICIOS DE CARGA Y/O REPARTO',56),
('ACTIVIDAD_ECONOMICA_PF','6330100','TRANSPORTE AEREO - COORDINADORES Y SUPERVISORES EN SERVICIOS DE TRANSPORTE AEREO',57),
('ACTIVIDAD_ECONOMICA_PF','6330200','TRANSPORTE AEREO - DESPACHADORES DE VUELO Y ESPECIALISTAS EN SERVICIOS AEREOS',58),
('ACTIVIDAD_ECONOMICA_PF','6330400','TRANSPORTE AEREO - SUPERVISORES DE SISTEMAS DE COMUNICACION PARA LA AERONAVEGACION',59),
('ACTIVIDAD_ECONOMICA_PF','6330500','TRANSPORTE AEREO - PILOTOS DE AVIACION E INSTRUCTORES DE VUELO',60),
('ACTIVIDAD_ECONOMICA_PF','6330600','TRANSPORTE AEREO - SOBRECARGOS',61),
('ACTIVIDAD_ECONOMICA_PF','6420100','TRANSPORTE MARITIMO Y FLUVIAL - CONDUCTORES DE EMBARCACIONES',62),
('ACTIVIDAD_ECONOMICA_PF','6430100','TRANSPORTE MARITIMO Y FLUVIAL - JEFES Y CONTROLADORES DE TRAFICO MARITIMO',63),
('ACTIVIDAD_ECONOMICA_PF','6430300','TRANSPORTE MARITIMO Y FLUVIAL - PILOTOS, CAPITANES DE PUERTOS Y OFICIALES DE CUBIERTA',64),
('ACTIVIDAD_ECONOMICA_PF','7110200','COMERCIO - DESPACHADORES DE GASOLINERA',65),
('ACTIVIDAD_ECONOMICA_PF','7110300','COMERCIO - EMPACADORES DE MERCANCIAS',66),
('ACTIVIDAD_ECONOMICA_PF','7110500','COMERCIO - TAQUILLEROS',67),
('ACTIVIDAD_ECONOMICA_PF','7110600','COMERCIO - VENDEDORES AMBULANTES',68),
('ACTIVIDAD_ECONOMICA_PF','7120100','COMERCIO - CAJEROS REGISTRADORES',69),
('ACTIVIDAD_ECONOMICA_PF','7130200','COMERCIO - REPRESENTANTES DE VENTAS POR TELEFONO O POR TELEVISION',70),
('ACTIVIDAD_ECONOMICA_PF','7130400','COMERCIO - VENDEDORES ESPECIALIZADOS',71),
('ACTIVIDAD_ECONOMICA_PF','7140100','COMERCIO - GERENTES O SUPERVISOR DE ESTABLECIMIENTO COMERCIAL',72),
('ACTIVIDAD_ECONOMICA_PF','7140200','COMERCIO - GERENTES O EMPLEADOS DE VENTAS',73),
('ACTIVIDAD_ECONOMICA_PF','7210100','ALIMENTACION Y HOSPEDAJE - TRABAJADORES DE SERVICIO DE ALIMENTOS Y BEBIDAS',74),
('ACTIVIDAD_ECONOMICA_PF','7230200','ALIMENTACION Y HOSPEDAJE - JEFES DE COCINA, RESTAURANTE Y/O BAR',75),
('ACTIVIDAD_ECONOMICA_PF','7240200','ALIMENTACION Y HOSPEDAJE - TRABAJADORES DE SERVICIOS DE ALOJAMIENTO',76),
('ACTIVIDAD_ECONOMICA_PF','7330200','TURISMO - COORDINADORES DE OPERACIONES EN AGENCIAS DE VIAJES',77),
('ACTIVIDAD_ECONOMICA_PF','7330300','TURISMO - GUIAS DE EXCURSIONES O ECOTURISTICO',78),
('ACTIVIDAD_ECONOMICA_PF','7430100','DEPORTE Y ESPARCIMIENTO - ANIMADORES RECREATIVOS',79),
('ACTIVIDAD_ECONOMICA_PF','7430200','DEPORTE Y ESPARCIMIENTO - ATLETAS, ENTRENADORES O INSTRUCTORES EN DEPORTE Y RECREACION',80),
('ACTIVIDAD_ECONOMICA_PF','7430400','DEPORTE Y ESPARCIMIENTO - OFICIALES, JUECES Y ARBITROS DEPORTIVOS',81),
('ACTIVIDAD_ECONOMICA_PF','7530100','SERVICIOS PERSONALES - ESTILISTAS, ESTETICISTAS Y MASAJISTAS',82),
('ACTIVIDAD_ECONOMICA_PF','7540100','SERVICIOS PERSONALES - TRBAJADORES DE SERVICIOS FUNERARIOS O CEMENTERIOS',83),
('ACTIVIDAD_ECONOMICA_PF','7620100','REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - CERRAJEROS',84),
('ACTIVIDAD_ECONOMICA_PF','7620200','REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - REPARADORES DE ARTICULOS DE HULE',85),
('ACTIVIDAD_ECONOMICA_PF','7630100','REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - RELOJEROS Y REPARADORES DE RELOJES',86),
('ACTIVIDAD_ECONOMICA_PF','7630200','REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - REPARADORES DE APARATOS ELECTRICOS',87),
('ACTIVIDAD_ECONOMICA_PF','7720100','LIMPIEZA - SERVICIOS DE CAMARISTAS Y ASEADORES',88),
('ACTIVIDAD_ECONOMICA_PF','7720200','LIMPIEZA - TRABAJADORES DE TINTORERIA Y LAVANDERIA',89),
('ACTIVIDAD_ECONOMICA_PF','7720300','LIMPIEZA - FUMIGADORES DE PLAGAS',90),
('ACTIVIDAD_ECONOMICA_PF','7810200','SERVICIO POSTAL Y MENSAJERIA - EMPLEADOS DE SERVICIOS DE MENSAJERIA',91),
('ACTIVIDAD_ECONOMICA_PF','8120100','BOLSA, BANCA Y SEGUROS - GERENTES O TRABAJADORES DE SERVICIOS Y PRODUCTOS FINANCIEROS',92),
('ACTIVIDAD_ECONOMICA_PF','8130500','BOLSA, BANCA Y SEGUROS - VALUADORES',93),
('ACTIVIDAD_ECONOMICA_PF','8140100','BOLSA, BANCA Y SEGUROS - AGENTES DE VALORES, PROMOTORES Y CORREDORES DE INVERSION',94),
('ACTIVIDAD_ECONOMICA_PF','8210100','ADMINISTRACION - TRABAJADORES DE ARCHIVO, ALMACEN DE INVENTARIOS',95),
('ACTIVIDAD_ECONOMICA_PF','8220400','ADMINISTRACION - CAPTURISTA Y OPERADORES DE TELEFONO',96),
('ACTIVIDAD_ECONOMICA_PF','8220600','ADMINISTRACION - PAGADORES Y COBRADORES',97),
('ACTIVIDAD_ECONOMICA_PF','8230300','ADMINISTRACION - DIRECTORES, GERENTES  Y EMPLEADOS DE COMPRAS, FINANZAS, RECURSOS HUMANOS Y SERVICIOS ADMINISTRATIVOS',98),
('ACTIVIDAD_ECONOMICA_PF','8240100','ADMINISTRACION - ASISTENTES ADMINISTRATIVOS',99),
('ACTIVIDAD_ECONOMICA_PF','8240200','ADMINISTRACION - CONTADORES Y AUDITORES',100),
('ACTIVIDAD_ECONOMICA_PF','8240600','ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE PRODUCCION',101),
('ACTIVIDAD_ECONOMICA_PF','8240700','ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE SERVICIOS DE TRANSPORTE',102),
('ACTIVIDAD_ECONOMICA_PF','8250100','ADMINISTRACION - CONSULTORES',103),
('ACTIVIDAD_ECONOMICA_PF','8250200','ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE COMERCIALIZACION',104),
('ACTIVIDAD_ECONOMICA_PF','8250800','ADMINISTRACION - DIRECTORES, GERENTES Y EMPELADOS ADMINISTRATIVOS',105),
('ACTIVIDAD_ECONOMICA_PF','8340100','SERVICIOS LEGALES - ABOGADOS Y ASESORES LEGALES',106),
('ACTIVIDAD_ECONOMICA_PF','8340300','SERVICIOS LEGALES - NOTARIOS Y CORREDORES PUBLICOS',107),
('ACTIVIDAD_ECONOMICA_PF','9120700','SERVICIOS MEDICOS - ENFERMERAS Y/O PARAMEDICOS',108),
('ACTIVIDAD_ECONOMICA_PF','9130300','SERVICIOS MEDICOS - DIETISTAS Y NUTRIOLOGOS',109),
('ACTIVIDAD_ECONOMICA_PF','9131200','SERVICIOS MEDICOS - TECNICOS DE LABORATORIO MEDICO',110),
('ACTIVIDAD_ECONOMICA_PF','9140200','SERVICIOS MEDICOS - DIRECTORES DE INSTITUCIONES EN EL CUIDADO DE LA SALUD',111),
('ACTIVIDAD_ECONOMICA_PF','9140400','SERVICIOS MEDICOS - FARMACEUTICOS',112),
('ACTIVIDAD_ECONOMICA_PF','9140500','SERVICIOS MEDICOS - FISIOTERAPEUTAS Y QUIROPRACTICOS',113),
('ACTIVIDAD_ECONOMICA_PF','9140700','SERVICIOS MEDICOS - MEDICOS ESPECIALISTAS',114),
('ACTIVIDAD_ECONOMICA_PF','9140800','SERVICIOS MEDICOS - MEDICOS GENERALES Y FAMILIARES',115),
('ACTIVIDAD_ECONOMICA_PF','9230100','INSPECCION - INSPECTORES DE SALUD AMBIENTAL, SANIDAD Y DEL TRABAJO',116),
('ACTIVIDAD_ECONOMICA_PF','9230200','INSPECCION - INSPECTORES DE TRANSPORTE DE CARGA Y DE PASAJEROS',117),
('ACTIVIDAD_ECONOMICA_PF','9230300','INSPECCION - INSPECTORES FISCALES Y DE PRECIOS',118),
('ACTIVIDAD_ECONOMICA_PF','9230400','INSPECCION - INSPECTORES SANITARIOS Y DE CONTROL DE CALIDAD DE PRODUCTOS CARNICOS, PESQUEROS Y AGRICOLAS',119),
('ACTIVIDAD_ECONOMICA_PF','9330100','SEGURIDAD SOCIAL - CONSEJEROS DE EMPLEO',120),
('ACTIVIDAD_ECONOMICA_PF','9330300','SEGURIDAD SOCIAL - TRABAJADORES DE SERVICIO SOCIAL Y DE LA COMUNIDAD',121),
('ACTIVIDAD_ECONOMICA_PF','9420100','PROTECCION DE BIENES Y/O PERSONAS - BOMBEROS',122),
('ACTIVIDAD_ECONOMICA_PF','9420300','PROTECCION DE BIENES Y/O PERSONAS - GUARDIAS DE SEGURIDAD',123),
('ACTIVIDAD_ECONOMICA_PF','9430100','PROTECCION DE BIENES Y/O PERSONAS - DETECTIVES PRIVADOS',124),
('ACTIVIDAD_ECONOMICA_PF','1014010','RADIO, CINE, TELEVISION Y TEATRO - DISEÑADORES GRAFICOS',125),
('ACTIVIDAD_ECONOMICA_PF','1014030','RADIO, CINE, TELEVISION Y TEATRO - EDITORES, PERIODISTAS, REPORTEROS Y REDACTORES',126),
('ACTIVIDAD_ECONOMICA_PF','1023010','RADIO, CINE, TELEVISION Y TEATRO - ASISTENTES Y/U OPERADORES DE PRODUCCION DE CINE, RADIO Y TELEVISION',127),
('ACTIVIDAD_ECONOMICA_PF','1023070','RADIO, CINE, TELEVISION Y TEATRO - LOCUTORES, COMENTARISTAS Y CRONISTAS DE RADIO Y TELEVISION',128),
('ACTIVIDAD_ECONOMICA_PF','1024020','RADIO, CINE, TELEVISION Y TEATRO - PRODUCTORES Y DIRECTORES DE CINE, TELEVISION Y TEATRO',129),
('ACTIVIDAD_ECONOMICA_PF','1033010','INTERPRETACION ARTISTICA - ACTORES, BAILARINES, MUSICOS, ESCRITORES',130),
('ACTIVIDAD_ECONOMICA_PF','1033020','INTERPRETACION ARTISTICA - ARTESANOS',131),
('ACTIVIDAD_ECONOMICA_PF','1033040','INTERPRETACION ARTISTICA - FOTOGRAFOS',132),
('ACTIVIDAD_ECONOMICA_PF','1034010','INTERPRETACION ARTISTICA - ARTISTAS PLASTICOS',133),
('ACTIVIDAD_ECONOMICA_PF','1044010','TRADUCCION E INTERPRETACION LINGüISTICA - INTERPRETES Y/O TRADUCTORES',134),
('ACTIVIDAD_ECONOMICA_PF','1052010','PUBLICIDAD, PROPAGANDA Y RELACIONES PUBLICAS - MODELOS Y EDECANES',135),
('ACTIVIDAD_ECONOMICA_PF','1054010','PUBLICIDAD, PROPAGANDA Y RELACIONES PUBLICAS - DIRECTORES, GERENTES Y EMPLEADOS DE PUBLICIDAD',136),
('ACTIVIDAD_ECONOMICA_PF','1112010','INVESTIGACION - ENCUESTADORES Y CODIFICADORES',137),
('ACTIVIDAD_ECONOMICA_PF','1113010','INVESTIGACION - ASISTENTES DE INVESTIGADORES',138),
('ACTIVIDAD_ECONOMICA_PF','1113020','INVESTIGACION - QUIMICOS Y/O TECNICOS EN QUIMICA',139),
('ACTIVIDAD_ECONOMICA_PF','1114010','INVESTIGACION - BIOLOGOS Y CIENTIFICOS RELACIONADOS',140),
('ACTIVIDAD_ECONOMICA_PF','1114020','INVESTIGACION - ECONOMISTAS Y POLITOLOGOS (NO FUNCIONARIOS PUBLICOS)',141),
('ACTIVIDAD_ECONOMICA_PF','1114030','INVESTIGACION - FISICOS ASTRONOMOS',142),
('ACTIVIDAD_ECONOMICA_PF','1114040','INVESTIGACION - GEOLOGOS, GEOQUIMICOS, GEOFISICOS Y GEOGRAFOS',143),
('ACTIVIDAD_ECONOMICA_PF','1114050','INVESTIGACION - INVESTIGADORES Y CONSULTORES EN MERCADOTECNIA',144),
('ACTIVIDAD_ECONOMICA_PF','1114060','INVESTIGACION - MATEMATICOS, ESTADISTICOS Y ACTUARIOS',145),
('ACTIVIDAD_ECONOMICA_PF','1114070','INVESTIGACION - METEOROLOGOS',146),
('ACTIVIDAD_ECONOMICA_PF','1114090','INVESTIGACION - SOCIOLOGOS, ANTROPOLOGOS E HISTORIADORES',147),
('ACTIVIDAD_ECONOMICA_PF','1123020','ENSEÑANZA - CAPACITADORES E INSTRUCTORES',148),
('ACTIVIDAD_ECONOMICA_PF','1124070','ENSEÑANZA - PROFESORES O DOCENTES',149),
('ACTIVIDAD_ECONOMICA_PF','1125010','ENSEÑANZA - DIRECTORES GENERALES DE EDUCACION',150),
('ACTIVIDAD_ECONOMICA_PF','1133010','DIFUSION CULTURAL - PROMOTORES DE DIFUSION CULTURAL',151),
('ACTIVIDAD_ECONOMICA_PF','1134010','DIFUSION CULTURAL - TRABAJADORES DE BIBLIOTECA, ARCHIVO, MUSEO Y GALERIA DE ARTE',152),
('ACTIVIDAD_ECONOMICA_PF','1135010','OTRAS OCUPACIONES - ESTUDIANTE O MENOR DE EDAD SIN OCUPACION',153),
('ACTIVIDAD_ECONOMICA_PF','1135080','OTRAS OCUPACIONES - PROPIETARIO, ACCIONISTA O SOCIO',154),
('ACTIVIDAD_ECONOMICA_PF','1135020','OTRAS OCUPACIONES - DESEMPLEADO',155),
('ACTIVIDAD_ECONOMICA_PF','1135030','OTRAS OCUPACIONES - JUBILADO O PENSIONADO',156),
('ACTIVIDAD_ECONOMICA_PF','1135050','OTRAS OCUPACIONES - AMA DE CASA O QUEHACERES DEL HOGAR',157),
('ACTIVIDAD_ECONOMICA_PF','1135060','OTRAS OCUPACIONES - MINISTROS DE CULTO RELIGIOSO (SACERDOTE, PASTOR, MONJA, ETC)',158),
('ACTIVIDAD_ECONOMICA_PF','1135070','OTRAS OCUPACIONES - AGENTE ADUANAL',159),
('ACTIVIDAD_ECONOMICA_PF','1136010','SECTOR PUBLICO - EMPLEADO DEL PODER EJECUTIVO FEDERAL',160),
('ACTIVIDAD_ECONOMICA_PF','1136020','SECTOR PUBLICO - EMPLEADO PODER EJECUTIVO ESTATAL O DEL DISTRITO FEDERAL',161),
('ACTIVIDAD_ECONOMICA_PF','1136030','SECTOR PUBLICO - EMPLEADO DEL PODER EJECUTIVO MUNICIPAL O DELEGACIONAL',162),
('ACTIVIDAD_ECONOMICA_PF','1136040','SECTOR PUBLICO - EMPLEADO DEL PODER JUDICIAL FEDERAL',163),
('ACTIVIDAD_ECONOMICA_PF','1136070','SECTOR PUBLICO - EMPLEADO DEL PODER JUDICIAL ESTATAL O DEL DISTRITO FEDERAL',164),
('ACTIVIDAD_ECONOMICA_PF','1136050','SECTOR PUBLICO - EMPLEADO DEL PODER LEGISLATIVO FEDERAL',165),
('ACTIVIDAD_ECONOMICA_PF','1136060','SECTOR PUBLICO - EMPLEADO DEL PODER LEGISLATIVO ESTATAL O DEL DISTRITO FEDERAL',166),
('ACTIVIDAD_ECONOMICA_PF','1136090','SECTOR PUBLICO - EJERCITO, ARMADA Y FUERZA AEREA',167),
('ACTIVIDAD_ECONOMICA_PF','1136080','ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES - EMPLEADOS DE ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES',168),
('GIRO_MERCANTIL_PM','1000000','NO APLICA',1),
('GIRO_MERCANTIL_PM','1100001','SECTOR PRIMARIO - AGRICULTURA',2),
('GIRO_MERCANTIL_PM','1200001','SECTOR PRIMARIO - GANADERIA',3),
('GIRO_MERCANTIL_PM','1300001','SECTOR PRIMARIO - EXPLOTACION DE OTROS ANIMALES (AVICULTURA, APICULTURA, ETC.)',4),
('GIRO_MERCANTIL_PM','1400002','SECTOR PRIMARIO - APROVECHAMIENTO FORESTAL',5),
('GIRO_MERCANTIL_PM','1500001','SECTOR PRIMARIO - PESCA',6),
('GIRO_MERCANTIL_PM','2100002','MINERIA - MINERIA DE OTROS RECURSOS',7),
('GIRO_MERCANTIL_PM','2200002','MINERIA - ACTIVIDADES RELACIONADAS CON EL PETROLEO Y EL GAS',8),
('GIRO_MERCANTIL_PM','2300003','MINERIA - ORO',9),
('GIRO_MERCANTIL_PM','2400002','MINERIA - PLATA',10),
('GIRO_MERCANTIL_PM','2500002','MINERIA - PIEDRAS PRECIOSAS',11),
('GIRO_MERCANTIL_PM','2600003','GENERACION, TRANSMISION Y DISTRIBUCION DE ENERGIA ELECTRICA, SUMINISTRO DE AGUA Y DE GAS',12),
('GIRO_MERCANTIL_PM','2710004','CONSTRUCCION - OTRAS ACTIVIDADES RELACIONADAS CON LA CONSTRUCCION',13),
('GIRO_MERCANTIL_PM','2720004','CONSTRUCCION - EDIFICACION RESIDENCIAL Y NO RESIDENCIAL',14),
('GIRO_MERCANTIL_PM','2730004','CONSTRUCCION - OBRAS DE INGENIERIA CIVIL',15),
('GIRO_MERCANTIL_PM','2740004','CONSTRUCCION - TRABAJOS ESPECIALIZADOS PARA LA CONSTRUCCION',16),
('GIRO_MERCANTIL_PM','2754004','CONSTRUCCION - SERVICIOS DE BLINDAJE PARCIAL O TOTAL DE INMUEBLES',17),
('GIRO_MERCANTIL_PM','3110005','INDUSTRIA - ALIMENTARIA',18),
('GIRO_MERCANTIL_PM','3120005','INDUSTRIA - BEBIDAS Y DEL TABACO',19),
('GIRO_MERCANTIL_PM','3140005','INDUSTRIA - PRODUCTOS TEXTILES',20),
('GIRO_MERCANTIL_PM','3150005','INDUSTRIA - PRENDAS DE VESTIR',21),
('GIRO_MERCANTIL_PM','3210005','INDUSTRIA - MADERA',22),
('GIRO_MERCANTIL_PM','3220005','INDUSTRIA - PAPEL',23),
('GIRO_MERCANTIL_PM','3230005','INDUSTRIA - IMPRESION E INDUSTRIAS CONEXAS',24),
('GIRO_MERCANTIL_PM','3240005','INDUSTRIA - PRODUCTOS DERIVADOS DEL PETROLEO Y DEL CARBON',25),
('GIRO_MERCANTIL_PM','3250005','INDUSTRIA - QUIMICA',26),
('GIRO_MERCANTIL_PM','3260005','INDUSTRIA - PLASTICO Y DEL HULE',27),
('GIRO_MERCANTIL_PM','3270005','INDUSTRIA - PRODUCTOS A BASE DE MINERALES NO METALICOS (ALFARERIA, PORCELANA, LOZA, VIDRIO, CEMENTO)',28),
('GIRO_MERCANTIL_PM','3310005','INDUSTRIA - METALICAS BASICAS',29),
('GIRO_MERCANTIL_PM','3320005','INDUSTRIA - PRODUCTOS METALICOS (HERRAMIENTAS, UTENSILIOS, ESTRUCTURAS, PIEZAS)',30),
('GIRO_MERCANTIL_PM','3330005','INDUSTRIA - MAQUINARIA Y EQUIPO',31),
('GIRO_MERCANTIL_PM','3340005','INDUSTRIA - EQUIPO DE COMPUTACION, COMUNICACION, MEDICION Y DE OTROS EQUIPOS, COMPONENTES Y ACCESORIOS ELECTRONICOS',32),
('GIRO_MERCANTIL_PM','3350005','INDUSTRIA - ACCESORIOS, APARATOS ELECTRICOS Y EQUIPO DE GENERACION DE ENERGIA ELECTRICA',33),
('GIRO_MERCANTIL_PM','3360005','INDUSTRIA - EQUIPO DE TRANSPORTE SIN MOTOR',34),
('GIRO_MERCANTIL_PM','3370005','INDUSTRIA - AUTOMOTRIZ',35),
('GIRO_MERCANTIL_PM','3380005','INDUSTRIA - VEHICULOS BLINDADOS Y EQUIPO PARA EL BLINDAJE DE VEHICULOS',36),
('GIRO_MERCANTIL_PM','3410005','INDUSTRIA - MUEBLES, COLCHONES Y PERSIANAS',37),
('GIRO_MERCANTIL_PM','3420005','INDUSTRIA - OTRAS INDUSTRIAS MANUFACTURERAS',38),
('GIRO_MERCANTIL_PM','3430005','INDUSTRIA - ORFEBRERIA Y JOYERIA DE METALES Y PIEDRAS PRECIOSOS',39),
('GIRO_MERCANTIL_PM','3440005','INDUSTRIA - JOYERIA DE METALES Y PIEDRAS NO PRECIOSOS Y DE OTROS MATERIALES',40),
('GIRO_MERCANTIL_PM','4310006','COMERCIO - ABARROTES, ALIMENTOS, BEBIDAS, HIELO Y TABACO',41),
('GIRO_MERCANTIL_PM','4320006','COMERCIO - PRODUCTOS FARMACEUTICOS, DE PERFUMERIA, ARTICULOS PARA EL ESPARCIMIENTO, ELECTRODOMESTICOS Y APARATOS DE LINEA BLANCA',42),
('GIRO_MERCANTIL_PM','4330006','COMERCIO - MATERIAS PRIMAS AGROPECUARIAS Y FORESTALES, PARA LA INDUSTRIA, Y MATERIALES DE DESECHO',43),
('GIRO_MERCANTIL_PM','4340006','COMERCIO - MAQUINARIA, EQUIPO DE COMPUTO Y MOBILIARIO DE USO GENERAL',44),
('GIRO_MERCANTIL_PM','4620006','COMERCIO - TIENDAS DE AUTOSERVICIO Y DEPARTAMENTALES',45),
('GIRO_MERCANTIL_PM','4630006','COMERCIO - PRODUCTOS TEXTILES, BISUTERIA, ACCESORIOS DE VESTIR Y CALZADO',46),
('GIRO_MERCANTIL_PM','4650006','COMERCIO - ARTICULOS DE PAPELERIA',47),
('GIRO_MERCANTIL_PM','4660026','COMERCIO - ARTICULOS DE JOYERIA Y RELOJES',48),
('GIRO_MERCANTIL_PM','4670006','COMERCIO - ARTICULOS PARA LA DECORACION DE INTERIORES',49),
('GIRO_MERCANTIL_PM','4680006','COMERCIO - ANTIGÜEDADES Y OBRAS DE ARTE',50),
('GIRO_MERCANTIL_PM','4710006','COMERCIO - ARTICULOS DE FERRETERIA, TLAPALERIA Y VIDRIOS',51),
('GIRO_MERCANTIL_PM','4720006','COMERCIO - VEHICULOS NUEVOS',52),
('GIRO_MERCANTIL_PM','4730006','COMERCIO - VEHICULOS USADOS',53),
('GIRO_MERCANTIL_PM','4740006','COMERCIO - PARTES Y REFACCIONES PARA VEHICULOS',54),
('GIRO_MERCANTIL_PM','4750006','COMERCIO - COMBUSTIBLES Y LUBRICANTES',55),
('GIRO_MERCANTIL_PM','4760006','COMERCIO - A TRAVES DE INTERNET, Y CATALOGOS IMPRESOS, TELEVISION Y SIMILARES',56),
('GIRO_MERCANTIL_PM','4810007','TRANSPORTE - AEREO',57),
('GIRO_MERCANTIL_PM','4820007','TRANSPORTE - FERROVIARIO',58),
('GIRO_MERCANTIL_PM','4830007','TRANSPORTE - MARITIMO Y FLUVIAL',59),
('GIRO_MERCANTIL_PM','4850007','TRANSPORTE - TERRESTRE',60),
('GIRO_MERCANTIL_PM','4860007','TRANSPORTE - TRANSPORTACION Y DISTRIBUCION POR DUCTOS',61),
('GIRO_MERCANTIL_PM','4880007','TRANSPORTE - SERVICIOS RELACIONADOS CON EL TRANSPORTE',62),
('GIRO_MERCANTIL_PM','4890007','TRANSPORTE - SERVICIOS DE AGENCIAS ADUANALES',63),
('GIRO_MERCANTIL_PM','4840007','TRANSPORTE - SERVICIOS DE TRANSPORTE Y/O CUSTODIA DE VALORES',64),
('GIRO_MERCANTIL_PM','4910008','SERVICIOS POSTALES',65),
('GIRO_MERCANTIL_PM','4920009','SERVICIOS DE MENSAJERIA Y PAQUETERIA',66),
('GIRO_MERCANTIL_PM','4930010','SERVICIOS DE ALMACENAMIENTO',67),
('GIRO_MERCANTIL_PM','5100011','INFORMACION EN MEDIOS MASIVOS',68),
('GIRO_MERCANTIL_PM','5180012','PROCESAMIENTO ELECTRONICO DE INFORMACION Y OTROS SERVICIOS WEB',69),
('GIRO_MERCANTIL_PM','5210013','SERVICIOS FINANCIEROS - BANCA CENTRAL',70),
('GIRO_MERCANTIL_PM','5220013','SERVICIOS FINANCIEROS - BANCA MULTIPLE',71),
('GIRO_MERCANTIL_PM','5230013','SERVICIOS FINANCIEROS - BANCA DE DESARROLLO',72),
('GIRO_MERCANTIL_PM','5240013','SERVICIOS FINANCIEROS - FONDOS Y FIDEICOMISOS FINANCIEROS',73),
('GIRO_MERCANTIL_PM','5250013','SERVICIOS FINANCIEROS - UNIONES DE CREDITO',74),
('GIRO_MERCANTIL_PM','5260013','SREVICIOS FINANCIEROS - CAJAS DE AHORRO POPULAR',75),
('GIRO_MERCANTIL_PM','5270013','SERVICIOS FINANCIEROS - OTRAS INSTITUCIONES DE INTERMEDIACION CREDITICIA Y FINANCIERA NO BURSATIL (OPERACION Y PROMOCION DE TARJETAS DE CREDITO NO BANCARIAS,  FINANCIAMIENTO DE BIENES DURADEROS), SOCIEDADES FINANCIERAS DE OBJETO LIMITADO',76),
('GIRO_MERCANTIL_PM','5280013','SERVICIOS FINANCIEROS - OTRAS INSTITUCIONES DE AHORRO Y PRESTAMO',77),
('GIRO_MERCANTIL_PM','5290013','SERVICIOS FINANCIEROS - COMPAÑIAS DE AUTOFINANCIAMIENTO',78),
('GIRO_MERCANTIL_PM','5310013','SERVICIOS FINANCIEROS - MONTEPIOS',79),
('GIRO_MERCANTIL_PM','5320013','SERVICIOS FINANCIEROS - CASAS DE EMPEÑO',80),
('GIRO_MERCANTIL_PM','5330013','SERVICIOS FINANCIEROS - SOCIEDADES FINANCIERAS DE OBJETO MULTIPLE',81),
('GIRO_MERCANTIL_PM','5350013','SERVICIOS FINANCIEROS - CASAS DE BOLSA',82),
('GIRO_MERCANTIL_PM','5360013','SERVICIOS FINANCIEROS - CASAS DE CAMBIO Y CENTROS CAMBIARIOS',83),
('GIRO_MERCANTIL_PM','5370013','SERVICIOS FINANCIEROS - TRANSMISORES DE DINERO',84),
('GIRO_MERCANTIL_PM','5390013','SERVICIOS FINANCIEROS - OTROS SERVICIOS RELACIONADOS CON LA INTERMEDIACION BURSATIL',85),
('GIRO_MERCANTIL_PM','5410013','SERVICIOS FINANCIEROS - COMPAÑIAS DE SEGUROS',86),
('GIRO_MERCANTIL_PM','5420013','SERVICIOS FINANCIEROS - COMPAÑIAS AFIANZADORAS',87),
('GIRO_MERCANTIL_PM','5430013','SERVICIOS FINANCIEROS - AGENTES, AJUSTADORES Y GESTORES DE SEGUROS Y FIANZAS',88),
('GIRO_MERCANTIL_PM','5440013','SERVICIOS FINANCIEROS - ADMINISTRACION DE FONDOS PARA EL RETIRO',89),
('GIRO_MERCANTIL_PM','5450013','SERVICIOS FINANCIEROS - EMISORA Y/O COMERCIALIZACION DE CHEQUES DE VIAJERO',90),
('GIRO_MERCANTIL_PM','5340013','OTRAS EMPRESAS DE INTERMEDIACION CREDITICIA NO FINANCIERAS',91),
('GIRO_MERCANTIL_PM','5510014','SERVICIOS INMOBILIARIOS Y DE ALQUILER - ALQUILER SIN INTERMEDIACION DE BIENES RAICES',92),
('GIRO_MERCANTIL_PM','5520014','SERVICIOS INMOBILIARIOS Y DE ALQUILER - INMOBILIARIAS Y CORREDORES DE BIENES RAICES',93),
('GIRO_MERCANTIL_PM','5530014','SERVICIOS INMOBILIARIOS Y DE ALQUILER - SERVICIOS DE ALQUILER DE BIENES MUEBLES EXCEPTO VEHICULOS',94),
('GIRO_MERCANTIL_PM','5540014','SERVICIOS INMOBILIARIOS Y DE ALQUILER - ALQUILER DE VEHICULOS',95),
('GIRO_MERCANTIL_PM','5550014','SERVICIOS INMOBILIARIOS Y DE ALQUILER - SERVICIOS DE ALQUILER DE MARCAS REGISTRADAS, PATENTES Y FRANQUICIAS',96),
('GIRO_MERCANTIL_PM','5610015','SERVICIOS PROFESIONALES Y TECNICOS - SERVICIOS JURIDICOS',97),
('GIRO_MERCANTIL_PM','5620015','SERVICIOS PROFESIONALES Y TECNICOS - NOTARIA Y CORREDURIA PUBLICA',98),
('GIRO_MERCANTIL_PM','5690015','SERVICIOS PROFESIONALES Y TECNICOS - CONTABILIDAD Y AUDITORIA',99),
('GIRO_MERCANTIL_PM','5630015','SERVICIOS PROFESIONALES Y TECNICOS - ARQUITECTURA, INGENIERIA Y ACTIVIDADES RELACIONADAS',100),
('GIRO_MERCANTIL_PM','5640015','SERVICIOS PROFESIONALES Y TECNICOS - DISEÑO DE SISTEMAS DE COMPUTO Y SERVICIOS RELACIONADOS',101),
('GIRO_MERCANTIL_PM','5650015','SERVICIOS PROFESIONALES Y TECNICOS - CONSULTORIA ADMINISTRATIVA, CIENTIFICA Y TECNICA',102),
('GIRO_MERCANTIL_PM','5660015','SERVICIOS PROFESIONALES Y TECNICOS - INVESTIGACION CIENTIFICA Y DESARROLLO',103),
('GIRO_MERCANTIL_PM','5670015','SERVICIOS PROFESIONALES Y TECNICOS - PUBLICIDAD Y ACTIVIDADES RELACIONADAS',104),
('GIRO_MERCANTIL_PM','5680015','SERVICIOS PROFESIONALES Y TECNICOS - OTROS SERVICIOS DE OUTSOURCING',105),
('GIRO_MERCANTIL_PM','5710016','SERVICIOS DE APOYO A LOS NEGOCIOS - SERVICIOS DE ADMINISTRACION DE NEGOCIOS',106),
('GIRO_MERCANTIL_PM','5720016','SERVICIOS DE APOYO A LOS NEGOCIOS - AGENCIAS DE COBRANZA, DESPACHOS DE INVESTIGACION',107),
('GIRO_MERCANTIL_PM','5730016','SERVICIOS DE APOYO A LOS NEGOCIOS - SERVICIOS DE PROTECCION Y SEGURIDAD',108),
('GIRO_MERCANTIL_PM','5740016','SERVICIOS DE APOYO A LOS NEGOCIOS - SERVICIOS DE LIMPIEZA Y MANTENIMIENTO',109),
('GIRO_MERCANTIL_PM','5750016','SERVICIOS DE APOYO A LOS NEGOCIOS - OTROS SERVICIOS',110),
('GIRO_MERCANTIL_PM','6100017','SERVICIOS EDUCATIVOS',111),
('GIRO_MERCANTIL_PM','6200018','SERVICIOS DE SALUD Y DE ASISTENCIA SOCIAL',112),
('GIRO_MERCANTIL_PM','7110019','SERVICIOS DE ESPARCIMIENTO CULTURALES Y DEPORTIVOS, Y OTROS SERVICIOS RECREATIVOS',113),
('GIRO_MERCANTIL_PM','7120019','SERVICIOS DE ESPARCIMIENTO - MUSEOS, SITIOS HISTORICOS, ZOOLOGICOS Y SIMILARES',114),
('GIRO_MERCANTIL_PM','7130019','SERVICIOS DE ESPARCIMIENTO - CASAS DE JUEGOS ELECTRONICOS',115),
('GIRO_MERCANTIL_PM','7140019','SERVICIOS DE ESPARCIMIENTO - CASINOS O CENTROS DE APUESTA',116),
('GIRO_MERCANTIL_PM','7150019','SERVICIOS DE ESPARCIMIENTO - VENTA DE BILLETES DE LOTERIA, PRONOSTICOS DEPORTIVOS U OTROS SORTEOS',117),
('GIRO_MERCANTIL_PM','7200020','SERVICIOS DE ALOJAMIENTO TEMPORAL Y DE PREPARACION DE ALIMENTOS Y BEBIDAS',118),
('GIRO_MERCANTIL_PM','8100021','SERVICIOS DE REPARACION Y MANTENIMIENTO - EQUIPO INDUSTRIAL, COMERCIAL, SERVICIOS Y AUTOMOTRIZ',119),
('GIRO_MERCANTIL_PM','8200022','SERVICIOS PERSONALES - LAVANDERIAS, SERVICIOS FUNERARIOS, BAÑOS PUBLICOS, SERVICIOS DE ESTACIONAMIENTO, REVELADO E IMPRESION DE FOTOGRAFIAS',120),
('GIRO_MERCANTIL_PM','8310023','ASOCIACIONES - ORGANIZACIONES Y CAMARAS DE PRODUCTORES, COMERCIANTES Y PRESTADORES DE SERVICIOS',121),
('GIRO_MERCANTIL_PM','8320023','ASOCIACIONES - ORGANIZACIONES LABORALES Y SINDICALES',122),
('GIRO_MERCANTIL_PM','8330023','ASOCIACIONES - ORGANIZACIONES DE PROFESIONISTAS',123),
('GIRO_MERCANTIL_PM','8340023','ASOCIACIONES - ORGANIZACIONES DE ACTIVIDADES RECREATIVAS',124),
('GIRO_MERCANTIL_PM','8350023','ASOCIACIONES - ORGANIZACIONES RELIGIOSAS',125),
('GIRO_MERCANTIL_PM','8360023','ASOCIACIONES - ORGANIZACIONES POLITICAS',126),
('GIRO_MERCANTIL_PM','8370023','ASOCIACIONES - ORGANIZACIONES CIVILES',127),
('GIRO_MERCANTIL_PM','9100025','ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES',128),
('GIRO_MERCANTIL_PM','9810024','SECTOR PUBLICO - PODER EJECUTIVO FEDERAL',129),
('GIRO_MERCANTIL_PM','9820024','SECTOR PUBLICO - PODER EJECUTIVO ESTATAL Y DEL DISTRITO FEDERAL',130),
('GIRO_MERCANTIL_PM','9830024','SECTOR PUBLICO - PODER EJECUTIVO MUNICIPAL Y DELEGACIONAL',131),
('GIRO_MERCANTIL_PM','9840024','SECTOR PUBLICO - PODER JUDICIAL FEDERAL',132),
('GIRO_MERCANTIL_PM','9850024','SECTOR PUBLICO - PODER JUDICIAL ESTATAL Y DEL DISTRITO FEDERAL',133),
('GIRO_MERCANTIL_PM','9860024','SECTOR PUBLICO - PODER LEGISLATIVO FEDERAL',134),
('GIRO_MERCANTIL_PM','9870024','SECTOR PUBLICO - PODER LEGISLATIVO ESTATAL Y DEL DISTRITO FEDERAL',135),
('GIRO_MERCANTIL_PM','9880024','SECTOR PUBLICO - ORGANOS AUTONOMOS Y ENTIDADES PARAESTATALES',136);
DO $$
BEGIN
  IF (SELECT pg_catalog.count(*) FROM expected_master_018 WHERE tipo_catalogo='ACTIVIDAD_ECONOMICA_PF')<>167
    OR (SELECT pg_catalog.count(*) FROM expected_master_018 WHERE tipo_catalogo='GIRO_MERCANTIL_PM')<>136 THEN
    RAISE EXCEPTION 'Conjunto canonico interno 018 invalido';
  END IF;
  IF (SELECT pg_catalog.count(*) FROM public.cat_actividades_economicas)<>167
    OR (SELECT pg_catalog.count(*) FROM public.cat_giros_mercantiles)<>136
    OR EXISTS (SELECT 1 FROM public.cat_actividades_economicas WHERE NOT activo)
    OR EXISTS (SELECT 1 FROM public.cat_giros_mercantiles WHERE NOT activo) THEN
    RAISE EXCEPTION 'Conteo o estado activo de catalogos incompatible';
  END IF;
  IF EXISTS (
    (SELECT clave::TEXT,descripcion::TEXT FROM public.cat_actividades_economicas
     EXCEPT SELECT clave,descripcion FROM expected_master_018 WHERE tipo_catalogo='ACTIVIDAD_ECONOMICA_PF')
    UNION ALL
    (SELECT clave,descripcion FROM expected_master_018 WHERE tipo_catalogo='ACTIVIDAD_ECONOMICA_PF'
     EXCEPT SELECT clave::TEXT,descripcion::TEXT FROM public.cat_actividades_economicas)
  ) OR EXISTS (
    (SELECT clave::TEXT,descripcion::TEXT FROM public.cat_giros_mercantiles
     EXCEPT SELECT clave,descripcion FROM expected_master_018 WHERE tipo_catalogo='GIRO_MERCANTIL_PM')
    UNION ALL
    (SELECT clave,descripcion FROM expected_master_018 WHERE tipo_catalogo='GIRO_MERCANTIL_PM'
     EXCEPT SELECT clave::TEXT,descripcion::TEXT FROM public.cat_giros_mercantiles)
  ) THEN
    RAISE EXCEPTION 'Contenido canonico clave/descripcion incompatible';
  END IF;
  IF EXISTS (
    SELECT 1 FROM expected_master_018 e
    LEFT JOIN public.cat_actividades_economicas p ON p.clave::TEXT=e.clave
    WHERE e.tipo_catalogo='ACTIVIDAD_ECONOMICA_PF' AND p.id IS DISTINCT FROM e.expected_id
  ) OR EXISTS (
    SELECT 1 FROM expected_master_018 e
    LEFT JOIN public.cat_giros_mercantiles m ON m.clave::TEXT=e.clave
    WHERE e.tipo_catalogo='GIRO_MERCANTIL_PM' AND m.id IS DISTINCT FROM e.expected_id
  ) THEN
    RAISE EXCEPTION 'IDs de claves reales fueron alterados';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.cat_actividades_economicas
    WHERE clave !~ '^[0-9]{7}$' OR pg_catalog.btrim(clave)<>clave
      OR pg_catalog.btrim(descripcion)='' OR pg_catalog.btrim(descripcion)<>descripcion
  ) OR EXISTS (
    SELECT 1 FROM public.cat_giros_mercantiles
    WHERE clave !~ '^[0-9]{7}$' OR pg_catalog.btrim(clave)<>clave
      OR pg_catalog.btrim(descripcion)='' OR pg_catalog.btrim(descripcion)<>descripcion
  ) THEN
    RAISE EXCEPTION 'Clave o descripcion canonica invalida';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.cat_actividades_economicas WHERE clave='1000000' AND descripcion='NO APLICA' AND activo)
    OR NOT EXISTS (SELECT 1 FROM public.cat_giros_mercantiles WHERE clave='1000000' AND descripcion='NO APLICA' AND activo)
    OR EXISTS (SELECT 1 FROM public.cat_actividades_economicas WHERE id=1 OR clave='Clave') THEN
    RAISE EXCEPTION 'Sentinela canonico o ausencia de fila espuria incompatible';
  END IF;
END
$$;
DO $$
BEGIN
  IF (SELECT pg_catalog.count(*) FROM public.clasificacion_actividad_pld_version)<>2
    OR (SELECT pg_catalog.count(*) FROM public.clasificacion_actividad_pld_item)<>99
    OR EXISTS (
      SELECT 1
      FROM public.clasificacion_actividad_pld_item i
      LEFT JOIN public.cat_actividades_economicas p
        ON i.tipo_catalogo='ACTIVIDAD_ECONOMICA_PF' AND p.clave::TEXT=i.clave_catalogo
      LEFT JOIN public.cat_giros_mercantiles m
        ON i.tipo_catalogo='GIRO_MERCANTIL_PM' AND m.clave::TEXT=i.clave_catalogo
      WHERE (i.tipo_catalogo='ACTIVIDAD_ECONOMICA_PF' AND p.id IS NULL)
         OR (i.tipo_catalogo='GIRO_MERCANTIL_PM' AND m.id IS NULL)
    ) THEN
    RAISE EXCEPTION 'Clasificaciones PLD huerfanas o alteradas';
  END IF;
  IF (SELECT pg_catalog.count(*) FROM public.clasificacion_actividad_pld_item WHERE marca_canonica='AV')<>38
    OR EXISTS (
      SELECT 1 FROM public.clasificacion_actividad_pld_item i
      LEFT JOIN public.cat_actividades_economicas p
        ON i.tipo_catalogo='ACTIVIDAD_ECONOMICA_PF' AND p.clave::TEXT=i.clave_catalogo AND p.activo
      LEFT JOIN public.cat_giros_mercantiles m
        ON i.tipo_catalogo='GIRO_MERCANTIL_PM' AND m.clave::TEXT=i.clave_catalogo AND m.activo
      WHERE i.marca_canonica='AV'
        AND (i.familia_av_id IS NULL
          OR (i.tipo_catalogo='ACTIVIDAD_ECONOMICA_PF' AND p.id IS NULL)
          OR (i.tipo_catalogo='GIRO_MERCANTIL_PM' AND m.id IS NULL))
    ) THEN
    RAISE EXCEPTION 'Asociaciones AV 017 huerfanas o alteradas';
  END IF;
END
$$;
CREATE TEMP TABLE expected_family_018(clave TEXT PRIMARY KEY,nombre TEXT NOT NULL,fraccion TEXT NOT NULL) ON COMMIT DROP;
INSERT INTO expected_family_018 VALUES
('AVG_JUEGOS_SORTEOS','Juegos, Apuestas y Sorteos','I'),
('AVG_TARJETAS_NO_BANCARIAS','Tarjetas No Bancarias','II y III'),
('AVG_FINANCIAMIENTO_NO_BANCARIO','Financiamiento No Bancario','IV'),
('AVG_SECTOR_INMOBILIARIO','Sector Inmobiliario','V y V Bis'),
('AVG_JOYERIA_RELOJES_METALES','Joyería, Relojes y Metales','VI'),
('AVG_ARTE_ANTIGUEDADES','Arte y Antigüedades','VII'),
('AVG_VEHICULOS','Vehículos','VIII'),
('AVG_BLINDAJE','Blindaje','IX'),
('AVG_SEGURIDAD_CUSTODIA','Seguridad y Custodia','X'),
('AVG_SERVICIOS_PROFESIONALES','Servicios Profesionales','XI'),
('AVG_FE_PUBLICA','Fe Pública (Notarios/Corredores)','XII'),
('AVG_DONATIVOS','Donativos (ONGs)','XIII'),
('AVG_AGENTES_ADUANALES','Agentes Aduanales','XIV'),
('AVG_ARRENDAMIENTO','Arrendamiento','XV'),
('AVG_ACTIVOS_VIRTUALES','Activos Virtuales (Cripto)','XVI');
CREATE TEMP TABLE expected_operation_018(operation_key TEXT PRIMARY KEY,family_key TEXT NOT NULL) ON COMMIT DROP;
INSERT INTO expected_operation_018 VALUES
('AV_VENTA_DE_BOLETOS_O_FICHAS_PARA_APUESTAS','AVG_JUEGOS_SORTEOS'),
('AV_CONCURSOS_O_SORTEOS','AVG_JUEGOS_SORTEOS'),
('AV_EMISION_O_COMERCIALIZACION_DE_TARJETAS_DE_CREDITO','AVG_TARJETAS_NO_BANCARIAS'),
('AV_EMISION_O_COMERCIALIZACION_DE_TARJETAS_DE_PREPAGO','AVG_TARJETAS_NO_BANCARIAS'),
('AV_OTORGAMIENTO_DE_MUTUO_O_PRESTAMOS','AVG_FINANCIAMIENTO_NO_BANCARIO'),
('AV_OTORGAMIENTO_DE_GARANTIAS','AVG_FINANCIAMIENTO_NO_BANCARIO'),
('AV_CONSTRUCCION_DE_INMUEBLES','AVG_SECTOR_INMOBILIARIO'),
('AV_DESARROLLO_DE_BIENES_INMUEBLES','AVG_SECTOR_INMOBILIARIO'),
('AV_INTERMEDIACION_EN_TRANSMISION_DE_PROPIEDAD','AVG_SECTOR_INMOBILIARIO'),
('AV_COMPRAVENTA_DE_INMUEBLES_A_NOMBRE_DEL_CLIENTE','AVG_SERVICIOS_PROFESIONALES'),
('AV_ARRENDAMIENTO_DE_BIENES_INMUEBLES','AVG_ARRENDAMIENTO'),
('AV_TRANSMISION_DE_DERECHOS_REALES_INMUEBLES','AVG_FE_PUBLICA'),
('AV_COMERCIALIZACION_DE_METALES_Y_PIEDRAS_PRECIOSAS','AVG_JOYERIA_RELOJES_METALES'),
('AV_COMERCIALIZACION_DE_JOYAS_O_RELOJES','AVG_JOYERIA_RELOJES_METALES'),
('AV_COMERCIALIZACION_DE_OBRAS_DE_ARTE','AVG_ARTE_ANTIGUEDADES'),
('AV_SUBASTA_DE_OBRAS_DE_ARTE','AVG_ARTE_ANTIGUEDADES'),
('AV_COMERCIALIZACION_DE_VEHICULOS_TERRESTRES','AVG_VEHICULOS'),
('AV_COMERCIALIZACION_DE_VEHICULOS_AEREOS','AVG_VEHICULOS'),
('AV_COMERCIALIZACION_DE_VEHICULOS_MARITIMOS','AVG_VEHICULOS'),
('AV_BLINDAJE_DE_VEHICULOS','AVG_BLINDAJE'),
('AV_BLINDAJE_DE_INMUEBLES','AVG_BLINDAJE'),
('AV_TRASLADO_O_CUSTODIA_DE_DINERO_Y_VALORES','AVG_SEGURIDAD_CUSTODIA'),
('AV_ADMINISTRACION_DE_RECURSOS_O_CUENTAS','AVG_SERVICIOS_PROFESIONALES'),
('AV_ORGANIZACION_DE_APORTACIONES_DE_CAPITAL','AVG_SERVICIOS_PROFESIONALES'),
('AV_CONSTITUCION_Y_ADMINISTRACION_DE_SOCIEDADES','AVG_SERVICIOS_PROFESIONALES'),
('AV_OTORGAMIENTO_DE_PODERES_PARA_ACTOS_DE_DOMINIO','AVG_FE_PUBLICA'),
('AV_CONSTITUCION_DE_PERSONAS_MORALES','AVG_FE_PUBLICA'),
('AV_RECEPCION_DE_DONATIVOS','AVG_DONATIVOS'),
('AV_DESPACHO_ADUANERO_DE_VEHICULOS','AVG_AGENTES_ADUANALES'),
('AV_DESPACHO_ADUANERO_DE_METALES_JOYAS_O_ARTE','AVG_AGENTES_ADUANALES'),
('AV_INTERCAMBIO_DE_ACTIVOS_VIRTUALES','AVG_ACTIVOS_VIRTUALES');
DO $$
BEGIN
  IF EXISTS (
    (SELECT clave,nombre,fraccion FROM public.cat_actividades_vulnerables_generales
     EXCEPT SELECT clave,nombre,fraccion FROM expected_family_018)
    UNION ALL
    (SELECT clave,nombre,fraccion FROM expected_family_018
     EXCEPT SELECT clave,nombre,fraccion FROM public.cat_actividades_vulnerables_generales)
  ) OR (SELECT pg_catalog.count(*) FROM public.cat_operaciones_vulnerables)<>31
    OR EXISTS (SELECT clave FROM public.cat_operaciones_vulnerables EXCEPT SELECT operation_key FROM expected_operation_018)
    OR EXISTS (SELECT operation_key FROM expected_operation_018 EXCEPT SELECT clave FROM public.cat_operaciones_vulnerables)
    OR (SELECT pg_catalog.count(*) FROM public.actividad_vulnerable_operaciones)<>31
    OR EXISTS (
      SELECT 1 FROM expected_operation_018 e
      LEFT JOIN public.cat_operaciones_vulnerables o ON o.clave=e.operation_key
      LEFT JOIN public.actividad_vulnerable_operaciones r ON r.operacion_vulnerable_id=o.id
      LEFT JOIN public.cat_actividades_vulnerables_generales f
        ON f.id=r.actividad_vulnerable_id AND f.clave=e.family_key
      WHERE f.id IS NULL
    ) OR EXISTS (
      SELECT operacion_vulnerable_id FROM public.actividad_vulnerable_operaciones
      GROUP BY operacion_vulnerable_id HAVING pg_catalog.count(*)<>1
    ) THEN
    RAISE EXCEPTION 'Jerarquia AV fue alterada';
  END IF;
END
$$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.cat_actividades_economicas WHERE id=1 OR clave='Clave') THEN
    RAISE EXCEPTION 'DOWN bloqueado: conflicto para restaurar fila legacy';
  END IF;
  INSERT INTO public.cat_actividades_economicas(
    id,clave,descripcion,activo,created_at,updated_at
  ) VALUES (
    1,'Clave','Actividad Económica',false,pg_catalog.now(),pg_catalog.now()
  );
  IF (SELECT pg_catalog.count(*) FROM public.cat_actividades_economicas)<>168
    OR (SELECT pg_catalog.count(*) FROM public.cat_actividades_economicas
        WHERE id=1 AND clave='Clave' AND descripcion='Actividad Económica' AND NOT activo)<>1
    OR (SELECT pg_catalog.count(*) FROM public.cat_actividades_economicas WHERE id<>1 AND activo)<>167
    OR (SELECT pg_catalog.count(*) FROM public.cat_giros_mercantiles)<>136
    OR EXISTS (SELECT 1 FROM public.cat_giros_mercantiles WHERE NOT activo) THEN
    RAISE EXCEPTION 'DOWN fallido: no se restauro el estado previo autorizado';
  END IF;
END
$$;

DELETE FROM public.schema_migrations
WHERE migration_key='20260822_018_catalogos_maestros_canonicos';

COMMIT;
