BEGIN;

SELECT pg_catalog.pg_advisory_xact_lock(
  pg_catalog.hashtext('20260817_011_clasificacion_geografica_pld')
);

DO $$
DECLARE
  required_key TEXT;
  expected RECORD;
  actual_columns TEXT[];
BEGIN
  IF pg_catalog.current_schema() IS DISTINCT FROM 'public' THEN
    RAISE EXCEPTION 'Esquema invalido: se esperaba public';
  END IF;

  IF pg_catalog.to_regclass('public.schema_migrations') IS NULL
     OR pg_catalog.to_regclass('public.usuarios') IS NULL
     OR pg_catalog.to_regclass('public.cat_paises') IS NULL THEN
    RAISE EXCEPTION 'Preflight fallido: falta schema_migrations, usuarios o cat_paises';
  END IF;

  FOREACH required_key IN ARRAY ARRAY[
    '20260728_001_modelo_integral_actividades_vulnerables',
    '20260801_002_matrices_pt_gr_empresa',
    '20260805_003_gestion_matrices_empresa',
    '20260810_004_resultados_globales_matriz',
    '20260812_005_catalogos_canonicos_matriz',
    '20260813_006_principales_tecnicos_usuarios',
    '20260813_007_seed_principal_sistema_y_catalogos_matriz',
    '20260815_008_descartar_borrador_matriz',
    '20260815_009_cliente_pt_evaluacion_matriz',
    '20260817_010_cliente_gr_evaluacion_matriz'
  ] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM public.schema_migrations sm WHERE sm.migration_key=required_key
    ) THEN
      RAISE EXCEPTION 'Dependencia faltante: %',required_key;
    END IF;
  END LOOP;

  IF EXISTS (
    SELECT 1 FROM public.schema_migrations
     WHERE migration_key='20260817_011_clasificacion_geografica_pld'
  ) THEN
    RAISE EXCEPTION 'La migracion 011 ya esta registrada';
  END IF;

  IF pg_catalog.to_regclass('public.clasificacion_geografica_pld_version') IS NOT NULL
     OR pg_catalog.to_regclass('public.clasificacion_geografica_pld_jurisdiccion') IS NOT NULL
     OR pg_catalog.to_regclass('public.clasificacion_geografica_pld_version_id_seq') IS NOT NULL
     OR pg_catalog.to_regclass('public.clasificacion_geografica_pld_jurisdiccion_id_seq') IS NOT NULL THEN
    RAISE EXCEPTION 'Estado parcial: ya existe un objeto introducido por 011';
  END IF;

  FOR expected IN
    SELECT * FROM (VALUES
      ('usuarios','id','pg_catalog.int4'::pg_catalog.regtype,-1,'p'),
      ('cat_paises','id','pg_catalog.int8'::pg_catalog.regtype,-1,'p'),
      ('cat_paises','clave','pg_catalog.varchar'::pg_catalog.regtype,14,'u')
    ) AS x(tabla,columna,tipo_oid,typmod,tipo_constraint)
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_catalog.pg_attribute a
       WHERE a.attrelid=pg_catalog.to_regclass('public.' || expected.tabla)
         AND a.attname=expected.columna AND a.attnum>0 AND NOT a.attisdropped
         AND a.atttypid=expected.tipo_oid AND a.atttypmod=expected.typmod
         AND a.attnotnull
    ) THEN
      RAISE EXCEPTION 'Preflight fallido: %.% incompatible',expected.tabla,expected.columna;
    END IF;

    SELECT ARRAY(
      SELECT a.attname::TEXT
        FROM pg_catalog.unnest(c.conkey) WITH ORDINALITY k(attnum,ord)
        JOIN pg_catalog.pg_attribute a
          ON a.attrelid=c.conrelid AND a.attnum=k.attnum
       ORDER BY k.ord
    ) INTO actual_columns
      FROM pg_catalog.pg_constraint c
     WHERE c.conrelid=pg_catalog.to_regclass('public.' || expected.tabla)
       AND c.contype=expected.tipo_constraint::"char" AND c.convalidated
       AND c.conkey=ARRAY[
         (SELECT a.attnum FROM pg_catalog.pg_attribute a
           WHERE a.attrelid=c.conrelid AND a.attname=expected.columna
             AND a.attnum>0 AND NOT a.attisdropped)
       ]::SMALLINT[];
    IF actual_columns IS DISTINCT FROM ARRAY[expected.columna]::TEXT[] THEN
      RAISE EXCEPTION 'Preflight fallido: constraint de %.% incompatible',expected.tabla,expected.columna;
    END IF;
  END LOOP;
END
$$;

CREATE TABLE public.clasificacion_geografica_pld_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tipo_clasificacion VARCHAR(40) NOT NULL,
  fuente_codigo VARCHAR(100) NOT NULL,
  fuente_nombre VARCHAR(255) NOT NULL,
  fuente_url TEXT,
  fuente_version VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  vigente_desde DATE NOT NULL,
  vigente_hasta DATE,
  activa BOOLEAN NOT NULL DEFAULT false,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT pg_catalog.now(),
  creado_por INTEGER NOT NULL,
  CONSTRAINT pk_clasificacion_geografica_pld_version PRIMARY KEY (id),
  CONSTRAINT uq_clasificacion_geografica_pld_version_fuente
    UNIQUE (tipo_clasificacion, fuente_codigo, fuente_version),
  CONSTRAINT fk_clasificacion_geografica_pld_version_creado_por
    FOREIGN KEY (creado_por) REFERENCES public.usuarios (id) ON DELETE RESTRICT,
  CONSTRAINT ck_clasificacion_geografica_pld_version_tipo CHECK (
    tipo_clasificacion IN (
      'GAFI_ALTO_RIESGO',
      'GAFI_LISTA_GRIS',
      'REGIMEN_FISCAL_PREFERENTE'
    )
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_version_fuente_codigo CHECK (
    fuente_codigo ~ '^[A-Z][A-Z0-9_]{0,99}$'
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_version_fuente_nombre CHECK (
    pg_catalog.btrim(fuente_nombre) <> ''
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_version_fuente_url CHECK (
    fuente_url IS NULL OR pg_catalog.btrim(fuente_url) <> ''
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_version_fuente_version CHECK (
    pg_catalog.btrim(fuente_version) <> ''
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_version_vigencia CHECK (
    fecha_publicacion <= vigente_desde
    AND (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde)
  )
);

CREATE UNIQUE INDEX uq_clasificacion_geografica_pld_version_tipo_activa
  ON public.clasificacion_geografica_pld_version (tipo_clasificacion)
  WHERE activa;

CREATE INDEX idx_clasificacion_geografica_pld_version_creado_por
  ON public.clasificacion_geografica_pld_version (creado_por);

CREATE TABLE public.clasificacion_geografica_pld_jurisdiccion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version_id BIGINT NOT NULL,
  pais_id BIGINT,
  jurisdiccion_codigo VARCHAR(100) NOT NULL,
  nombre_fuente VARCHAR(255) NOT NULL,
  nombre_normalizado VARCHAR(255) NOT NULL,
  tipo_entidad_geografica VARCHAR(20) NOT NULL,
  observacion TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT pg_catalog.now(),
  CONSTRAINT pk_clasificacion_geografica_pld_jurisdiccion PRIMARY KEY (id),
  CONSTRAINT uq_clasificacion_geografica_pld_jurisdiccion_version_codigo
    UNIQUE (version_id, jurisdiccion_codigo),
  CONSTRAINT fk_clasificacion_geografica_pld_jurisdiccion_version
    FOREIGN KEY (version_id)
    REFERENCES public.clasificacion_geografica_pld_version (id) ON DELETE RESTRICT,
  CONSTRAINT fk_clasificacion_geografica_pld_jurisdiccion_pais
    FOREIGN KEY (pais_id) REFERENCES public.cat_paises (id) ON DELETE RESTRICT,
  CONSTRAINT ck_clasificacion_geografica_pld_jurisdiccion_codigo CHECK (
    jurisdiccion_codigo ~ '^[A-Z0-9][A-Z0-9_.-]{0,99}$'
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_jurisdiccion_nombre_fuente CHECK (
    pg_catalog.btrim(nombre_fuente) <> ''
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_jurisdiccion_nombre_normalizado CHECK (
    pg_catalog.btrim(nombre_normalizado) <> ''
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_jurisdiccion_tipo CHECK (
    tipo_entidad_geografica IN ('PAIS','TERRITORIO','ZONA')
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_jurisdiccion_pais_requerido CHECK (
    tipo_entidad_geografica <> 'PAIS' OR pais_id IS NOT NULL
  ),
  CONSTRAINT ck_clasificacion_geografica_pld_jurisdiccion_observacion CHECK (
    observacion IS NULL OR pg_catalog.btrim(observacion) <> ''
  )
);

CREATE UNIQUE INDEX uq_clasificacion_geografica_pld_jurisdiccion_version_pais
  ON public.clasificacion_geografica_pld_jurisdiccion (version_id,pais_id)
  WHERE pais_id IS NOT NULL;

CREATE INDEX idx_clasificacion_geografica_pld_jurisdiccion_pais
  ON public.clasificacion_geografica_pld_jurisdiccion (pais_id)
  WHERE pais_id IS NOT NULL;

INSERT INTO public.schema_migrations (migration_key)
VALUES ('20260817_011_clasificacion_geografica_pld');

COMMIT;
