BEGIN; SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('20260817_013_seed_clasificacion_actividad_pld'));
DO $$ DECLARE d text; BEGIN
IF NOT EXISTS(SELECT 1 FROM public.schema_migrations WHERE migration_key='20260817_013_seed_clasificacion_actividad_pld') THEN RAISE EXCEPTION '013 ausente'; END IF;
IF (SELECT count(*) FROM public.clasificacion_actividad_pld_version WHERE fuente_version='20260817_INICIAL' AND activa AND vigente_desde=DATE '2026-08-17' AND fecha_publicacion IS NULL)<>2 THEN RAISE EXCEPTION 'Versiones incompatibles'; END IF;
IF (SELECT count(*) FROM public.clasificacion_actividad_pld_version WHERE (tipo_catalogo,fuente_codigo,fuente_nombre,fuente_version) IN (('ACTIVIDAD_ECONOMICA_PF','PLD_VISSION_ACTIVIDAD_ECONOMICA_PF','Actividad economica PF.xlsx','20260817_INICIAL'),('GIRO_MERCANTIL_PM','PLD_VISSION_GIRO_MERCANTIL_PM','Giro mercantil PM.xlsx','20260817_INICIAL')))<>2 THEN RAISE EXCEPTION 'DOWN bloqueado: fuentes modificadas'; END IF;
IF EXISTS(SELECT 1 FROM public.cliente_gr_criterio_resultado WHERE resolver_codigo='ACTIVIDAD_ECONOMICA') THEN RAISE EXCEPTION 'DOWN bloqueado: el seed 013 ya fue utilizado por evaluaciones historicas de ACTIVIDAD_ECONOMICA'; END IF;
SELECT md5(string_agg(concat_ws('|',v.tipo_catalogo,i.clave_catalogo,i.descripcion_fuente,i.marca_canonica,coalesce(i.categoria_fuente,'')),E'\n' ORDER BY v.tipo_catalogo,i.clave_catalogo,i.descripcion_fuente,i.marca_canonica,coalesce(i.categoria_fuente,''))) INTO d FROM public.clasificacion_actividad_pld_version v JOIN public.clasificacion_actividad_pld_item i ON i.version_id=v.id WHERE v.fuente_version='20260817_INICIAL'; IF d<>'9a4c36ea5c0e8fde9ccb32e86d7e67fa' THEN RAISE EXCEPTION 'Contenido seed modificado'; END IF;
END $$;
DELETE FROM public.clasificacion_actividad_pld_item i USING public.clasificacion_actividad_pld_version v WHERE i.version_id=v.id AND v.fuente_version='20260817_INICIAL' AND v.fuente_codigo IN ('PLD_VISSION_ACTIVIDAD_ECONOMICA_PF','PLD_VISSION_GIRO_MERCANTIL_PM'); DELETE FROM public.clasificacion_actividad_pld_version WHERE fuente_version='20260817_INICIAL' AND fuente_codigo IN ('PLD_VISSION_ACTIVIDAD_ECONOMICA_PF','PLD_VISSION_GIRO_MERCANTIL_PM'); DELETE FROM public.schema_migrations WHERE migration_key='20260817_013_seed_clasificacion_actividad_pld'; COMMIT;
