BEGIN;

SELECT pg_catalog.pg_advisory_xact_lock(
  pg_catalog.hashtext('20260817_012_clasificacion_actividad_pld')
);

DO $$
DECLARE
  required_key TEXT;
  catalog_table TEXT;
  actual_columns TEXT[];
BEGIN
  IF pg_catalog.current_schema() IS DISTINCT FROM 'public' THEN
    RAISE EXCEPTION 'Esquema invalido: se esperaba public';
  END IF;

  FOREACH catalog_table IN ARRAY ARRAY[
    'schema_migrations','usuarios','cat_actividades_economicas','cat_giros_mercantiles'
  ] LOOP
    IF pg_catalog.to_regclass('public.' || catalog_table) IS NULL THEN
      RAISE EXCEPTION 'Preflight fallido: falta public.%',catalog_table;
    END IF;
  END LOOP;

  FOREACH required_key IN ARRAY ARRAY[
    '20260728_001_modelo_integral_actividades_vulnerables',
    '20260801_002_matrices_pt_gr_empresa',
    '20260805_003_gestion_matrices_empresa',
    '20260810_004_resultados_globales_matriz',
    '20260812_005_catalogos_canonicos_matriz',
    '20260813_006_principales_tecnicos_usuarios',
    '20260813_007_seed_principal_sistema_y_catalogos_matriz',
    '20260815_008_descartar_borrador_matriz',
    '20260815_009_cliente_pt_evaluacion_matriz',
    '20260817_010_cliente_gr_evaluacion_matriz',
    '20260817_011_clasificacion_geografica_pld'
  ] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM public.schema_migrations sm WHERE sm.migration_key=required_key
    ) THEN
      RAISE EXCEPTION 'Dependencia faltante: %',required_key;
    END IF;
  END LOOP;

  IF EXISTS (
    SELECT 1 FROM public.schema_migrations
     WHERE migration_key='20260817_012_clasificacion_actividad_pld'
  ) THEN
    RAISE EXCEPTION 'La migracion 012 ya esta registrada';
  END IF;

  IF pg_catalog.to_regclass('public.clasificacion_actividad_pld_version') IS NOT NULL
     OR pg_catalog.to_regclass('public.clasificacion_actividad_pld_item') IS NOT NULL
     OR pg_catalog.to_regclass('public.clasificacion_actividad_pld_version_id_seq') IS NOT NULL
     OR pg_catalog.to_regclass('public.clasificacion_actividad_pld_item_id_seq') IS NOT NULL THEN
    RAISE EXCEPTION 'Estado parcial: ya existe un objeto introducido por 012';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_attribute a
     WHERE a.attrelid='public.usuarios'::pg_catalog.regclass
       AND a.attname='id' AND a.attnum>0 AND NOT a.attisdropped
       AND a.atttypid='pg_catalog.int4'::pg_catalog.regtype AND a.attnotnull
  ) OR NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_constraint c
     WHERE c.conrelid='public.usuarios'::pg_catalog.regclass
       AND c.contype='p' AND c.convalidated
       AND c.conkey=ARRAY[
         (SELECT a.attnum FROM pg_catalog.pg_attribute a
           WHERE a.attrelid=c.conrelid AND a.attname='id'
             AND a.attnum>0 AND NOT a.attisdropped)
       ]::SMALLINT[]
  ) THEN
    RAISE EXCEPTION 'Preflight fallido: usuarios.id incompatible';
  END IF;

  FOREACH catalog_table IN ARRAY ARRAY[
    'cat_actividades_economicas','cat_giros_mercantiles'
  ] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_catalog.pg_attribute a
       WHERE a.attrelid=pg_catalog.to_regclass('public.' || catalog_table)
         AND a.attname='clave' AND a.attnum>0 AND NOT a.attisdropped
         AND a.atttypid IN (
           'pg_catalog.text'::pg_catalog.regtype,
           'pg_catalog.varchar'::pg_catalog.regtype,
           'pg_catalog.bpchar'::pg_catalog.regtype
         ) AND a.attnotnull
    ) THEN
      RAISE EXCEPTION 'Preflight fallido: %.clave no es texto NOT NULL',catalog_table;
    END IF;

    SELECT ARRAY(
      SELECT a.attname::TEXT
        FROM pg_catalog.unnest(c.conkey) WITH ORDINALITY k(attnum,ord)
        JOIN pg_catalog.pg_attribute a
          ON a.attrelid=c.conrelid AND a.attnum=k.attnum
       ORDER BY k.ord
    ) INTO actual_columns
      FROM pg_catalog.pg_constraint c
     WHERE c.conrelid=pg_catalog.to_regclass('public.' || catalog_table)
       AND c.contype IN ('p','u') AND c.convalidated
       AND c.conkey=ARRAY[
         (SELECT a.attnum FROM pg_catalog.pg_attribute a
           WHERE a.attrelid=c.conrelid AND a.attname='clave'
             AND a.attnum>0 AND NOT a.attisdropped)
       ]::SMALLINT[];
    IF actual_columns IS DISTINCT FROM ARRAY['clave']::TEXT[] THEN
      RAISE EXCEPTION 'Preflight fallido: %.clave no es unica',catalog_table;
    END IF;
  END LOOP;
END
$$;

CREATE TABLE public.clasificacion_actividad_pld_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tipo_catalogo VARCHAR(30) NOT NULL,
  fuente_codigo VARCHAR(100) NOT NULL,
  fuente_nombre VARCHAR(255) NOT NULL,
  fuente_version VARCHAR(100) NOT NULL,
  fecha_publicacion DATE,
  vigente_desde DATE NOT NULL,
  vigente_hasta DATE,
  activa BOOLEAN NOT NULL DEFAULT false,
  creada_por INTEGER NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT pg_catalog.now(),
  CONSTRAINT pk_clasificacion_actividad_pld_version PRIMARY KEY (id),
  CONSTRAINT uq_clasificacion_actividad_pld_version_fuente
    UNIQUE (tipo_catalogo,fuente_codigo,fuente_version),
  CONSTRAINT uq_clasificacion_actividad_pld_version_id_tipo
    UNIQUE (id,tipo_catalogo),
  CONSTRAINT fk_clasificacion_actividad_pld_version_creada_por
    FOREIGN KEY (creada_por) REFERENCES public.usuarios (id) ON DELETE RESTRICT,
  CONSTRAINT ck_clasificacion_actividad_pld_version_tipo CHECK (
    tipo_catalogo IN ('ACTIVIDAD_ECONOMICA_PF','GIRO_MERCANTIL_PM')
  ),
  CONSTRAINT ck_clasificacion_actividad_pld_version_fuente_codigo CHECK (
    fuente_codigo ~ '^[A-Z][A-Z0-9_]{0,99}$'
  ),
  CONSTRAINT ck_clasificacion_actividad_pld_version_fuente_nombre CHECK (
    pg_catalog.btrim(fuente_nombre) <> ''
  ),
  CONSTRAINT ck_clasificacion_actividad_pld_version_fuente_version CHECK (
    pg_catalog.btrim(fuente_version) <> ''
  ),
  CONSTRAINT ck_clasificacion_actividad_pld_version_vigencia CHECK (
    (fecha_publicacion IS NULL OR fecha_publicacion <= vigente_desde)
    AND (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde)
  )
);

CREATE UNIQUE INDEX uq_clasificacion_actividad_pld_version_tipo_activa
  ON public.clasificacion_actividad_pld_version (tipo_catalogo)
  WHERE activa;

CREATE INDEX idx_clasificacion_actividad_pld_version_creada_por
  ON public.clasificacion_actividad_pld_version (creada_por);

CREATE TABLE public.clasificacion_actividad_pld_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version_id BIGINT NOT NULL,
  tipo_catalogo VARCHAR(30) NOT NULL,
  clave_catalogo TEXT NOT NULL,
  descripcion_fuente VARCHAR(255) NOT NULL,
  marca_canonica VARCHAR(30) NOT NULL,
  categoria_fuente VARCHAR(150),
  observacion TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT pg_catalog.now(),
  CONSTRAINT pk_clasificacion_actividad_pld_item PRIMARY KEY (id),
  CONSTRAINT uq_clasificacion_actividad_pld_item_version_clave_marca
    UNIQUE (version_id,clave_catalogo,marca_canonica),
  CONSTRAINT fk_clasificacion_actividad_pld_item_version
    FOREIGN KEY (version_id,tipo_catalogo)
    REFERENCES public.clasificacion_actividad_pld_version (id,tipo_catalogo)
    ON DELETE RESTRICT,
  CONSTRAINT ck_clasificacion_actividad_pld_item_clave CHECK (
    pg_catalog.btrim(clave_catalogo) <> ''
    AND clave_catalogo=pg_catalog.btrim(clave_catalogo)
  ),
  CONSTRAINT ck_clasificacion_actividad_pld_item_descripcion CHECK (
    pg_catalog.btrim(descripcion_fuente) <> ''
  ),
  CONSTRAINT ck_clasificacion_actividad_pld_item_marca CHECK (
    marca_canonica IN ('AV','HUACHICOL','DOBLE_USO','PEP','PEP_EXTRANJERO','OSFL')
  ),
  CONSTRAINT ck_clasificacion_actividad_pld_item_marca_tipo CHECK (
    tipo_catalogo IN ('ACTIVIDAD_ECONOMICA_PF','GIRO_MERCANTIL_PM')
    AND (marca_canonica <> 'PEP_EXTRANJERO'
         OR tipo_catalogo='ACTIVIDAD_ECONOMICA_PF')
    AND (marca_canonica <> 'OSFL'
         OR tipo_catalogo='GIRO_MERCANTIL_PM')
  ),
  CONSTRAINT ck_clasificacion_actividad_pld_item_categoria CHECK (
    categoria_fuente IS NULL OR pg_catalog.btrim(categoria_fuente) <> ''
  ),
  CONSTRAINT ck_clasificacion_actividad_pld_item_observacion CHECK (
    observacion IS NULL OR pg_catalog.btrim(observacion) <> ''
  )
);

CREATE INDEX idx_clasificacion_actividad_pld_item_clave
  ON public.clasificacion_actividad_pld_item (clave_catalogo);

INSERT INTO public.schema_migrations (migration_key)
VALUES ('20260817_012_clasificacion_actividad_pld');

COMMIT;
