BEGIN; SET TRANSACTION READ ONLY;
DO $$ DECLARE d text; BEGIN
IF NOT EXISTS(SELECT 1 FROM public.schema_migrations WHERE migration_key='20260817_013_seed_clasificacion_actividad_pld') THEN RAISE EXCEPTION '013 ausente'; END IF;
IF (SELECT count(*) FROM public.clasificacion_actividad_pld_version WHERE fuente_version='20260817_INICIAL' AND activa AND vigente_desde=DATE '2026-08-17' AND fecha_publicacion IS NULL)<>2 THEN RAISE EXCEPTION 'Versiones incompatibles'; END IF;
IF (SELECT count(*) FROM public.clasificacion_actividad_pld_version WHERE (tipo_catalogo,fuente_codigo,fuente_nombre,fuente_version) IN (('ACTIVIDAD_ECONOMICA_PF','PLD_VISSION_ACTIVIDAD_ECONOMICA_PF','Actividad economica PF.xlsx','20260817_INICIAL'),('GIRO_MERCANTIL_PM','PLD_VISSION_GIRO_MERCANTIL_PM','Giro mercantil PM.xlsx','20260817_INICIAL')))<>2 THEN RAISE EXCEPTION 'Fuentes incompatibles'; END IF;
IF EXISTS(SELECT 1 FROM public.clasificacion_actividad_pld_version v JOIN public.clasificacion_actividad_pld_item i ON i.version_id=v.id LEFT JOIN public.cat_actividades_economicas p ON v.tipo_catalogo='ACTIVIDAD_ECONOMICA_PF' AND p.clave::text=i.clave_catalogo LEFT JOIN public.cat_giros_mercantiles m ON v.tipo_catalogo='GIRO_MERCANTIL_PM' AND m.clave::text=i.clave_catalogo WHERE v.fuente_version='20260817_INICIAL' AND ((v.tipo_catalogo='ACTIVIDAD_ECONOMICA_PF' AND p.clave IS NULL) OR (v.tipo_catalogo='GIRO_MERCANTIL_PM' AND m.clave IS NULL))) THEN RAISE EXCEPTION 'Clave huerfana'; END IF;
IF EXISTS(SELECT 1 FROM public.clasificacion_actividad_pld_version v JOIN public.clasificacion_actividad_pld_item i ON i.version_id=v.id WHERE v.fuente_version='20260817_INICIAL' AND (i.marca_canonica NOT IN ('AV','HUACHICOL','DOBLE_USO','PEP','PEP_EXTRANJERO','OSFL') OR (i.marca_canonica='PEP_EXTRANJERO' AND i.tipo_catalogo<>'ACTIVIDAD_ECONOMICA_PF') OR (i.marca_canonica='OSFL' AND i.tipo_catalogo<>'GIRO_MERCANTIL_PM'))) THEN RAISE EXCEPTION 'Marca incompatible'; END IF;
IF EXISTS((VALUES ('ACTIVIDAD_ECONOMICA_PF','AV',4),('ACTIVIDAD_ECONOMICA_PF','HUACHICOL',2),('ACTIVIDAD_ECONOMICA_PF','DOBLE_USO',32),('ACTIVIDAD_ECONOMICA_PF','PEP',8),('GIRO_MERCANTIL_PM','AV',34),('GIRO_MERCANTIL_PM','HUACHICOL',3),('GIRO_MERCANTIL_PM','DOBLE_USO',1),('GIRO_MERCANTIL_PM','PEP',8),('GIRO_MERCANTIL_PM','OSFL',7)) EXCEPT SELECT i.tipo_catalogo,i.marca_canonica,count(*)::integer FROM public.clasificacion_actividad_pld_version v JOIN public.clasificacion_actividad_pld_item i ON i.version_id=v.id WHERE v.fuente_version='20260817_INICIAL' GROUP BY i.tipo_catalogo,i.marca_canonica) THEN RAISE EXCEPTION 'Conteos por marca incompatibles'; END IF;
IF (SELECT count(DISTINCT (i.tipo_catalogo,i.clave_catalogo)) FROM public.clasificacion_actividad_pld_version v JOIN public.clasificacion_actividad_pld_item i ON i.version_id=v.id WHERE v.fuente_version='20260817_INICIAL')<>99 OR NOT EXISTS(SELECT 1 FROM public.clasificacion_actividad_pld_version v JOIN public.clasificacion_actividad_pld_item i ON i.version_id=v.id WHERE v.fuente_version='20260817_INICIAL' AND i.tipo_catalogo='ACTIVIDAD_ECONOMICA_PF' AND i.clave_catalogo IN ('2210100','2240200') AND i.marca_canonica='HUACHICOL' GROUP BY i.marca_canonica HAVING count(*)=2) THEN RAISE EXCEPTION 'Cobertura de claves incompatible'; END IF;
SELECT md5(string_agg(concat_ws('|',v.tipo_catalogo,i.clave_catalogo,i.descripcion_fuente,i.marca_canonica,coalesce(i.categoria_fuente,'')),E'\n' ORDER BY v.tipo_catalogo,i.clave_catalogo,i.descripcion_fuente,i.marca_canonica,coalesce(i.categoria_fuente,''))) INTO d FROM public.clasificacion_actividad_pld_version v JOIN public.clasificacion_actividad_pld_item i ON i.version_id=v.id WHERE v.fuente_version='20260817_INICIAL'; IF d<>'9a4c36ea5c0e8fde9ccb32e86d7e67fa' THEN RAISE EXCEPTION 'Contenido seed modificado'; END IF;
END $$;
ROLLBACK;
